server:
  port: 8080

spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
        - id: patient-service
          uri: lb://patient-service
          predicates:
            - Path=/api/patients/**
        - id: doctor-service
          uri: lb://doctor-service
          predicates:
            - Path=/api/doctors/**
        - id: bed-service
          uri: lb://bed-service
          predicates:
            - Path=/api/beds/**
        - id: pharmacy-service
          uri: lb://pharmacy-service
          predicates:
            - Path=/api/pharmacy/**
        - id: emergency-service
          uri: lb://emergency-service
          predicates:
            - Path=/api/emergency/**
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/notifications/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/